

class Constants:
    SOUND_CLICK_LOUD = "SOUND_CLICK1"
    SOUND_CLICK_SHORT = "SOUND_CLICK_SHORT"
    SOUND_CLICK_SILENT = "SOUND_CLICK_SILENT"
    SOUND_CLICK_PEN = "SOUND_CLICK_PEN"
    SOUND_CREATED = "SOUND_CREATED"
    SOUND_CREATING = "SOUND_CREATING"
    SOUND_STEP = "SOUND_STEP"
    SOUND_DELETE = "SOUND_DELETE"
    SOUND_MOVE = "SOUND_MOVE"
    
    
    
   

    